# Generated by Django 5.2.2 on 2025-12-20 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('kcal_per_100g', models.DecimalField(decimal_places=2, max_digits=7)),
                ('protein_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('fat_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('carb_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('source', models.CharField(choices=[('manual', 'Вручную'), ('openfoodfacts', 'OpenFoodFacts')], default='manual', max_length=32)),
                ('external_id', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('snack', 'Перекус')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'type', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nutrition.fooditem')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition.meal')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('target_date', models.DateField(blank=True, null=True)),
                ('start_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('target_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('daily_kcal_target', models.PositiveIntegerField()),
                ('daily_protein_target', models.PositiveIntegerField(blank=True, null=True)),
                ('daily_fat_target', models.PositiveIntegerField(blank=True, null=True)),
                ('daily_carb_target', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', '-start_date', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='uniq_active_goal')],
            },
        ),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.UniqueConstraint(fields=('user', 'date', 'type'), name='uniq_meal_per_day_type'),
        ),
        migrations.AddConstraint(
            model_name='weightlog',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='uniq_weightlog_per_day'),
        ),
    ]
